#!/bin/bash

BASE_DIR="$HOME/MP3"
URL="$1"
CATEGORY="$2"
NAME_INPUT="$3"

case "$CATEGORY" in
    m) DEST_DIR="$BASE_DIR/music" ;;
    p) DEST_DIR="$BASE_DIR/podcasts" ;;
    *) notify-send "Error" "Use m or p"; exit 1 ;;
esac

mkdir -p "$DEST_DIR"

if [[ -z "$NAME_INPUT" ]]; then
    OUTPUT_TEMPLATE="$DEST_DIR/%(title)s.%(ext)s"
else
    OUTPUT_TEMPLATE="$DEST_DIR/$NAME_INPUT.%(ext)s"
fi

# THE PROGRESS LOGIC
# This sends a starting notification and captures its ID (if supported)
notify-send -t 2000 "Download Initializing" "Connecting to YouTube..."

# We use a custom --progress-template to send notifications every few seconds
# Note: On some systems, this may flood notifications; we'll keep it clean.
yt-dlp -x --audio-format mp3 --audio-quality 0 \
    --continue --no-overwrites \
    --progress-template "download:notify-send -t 1000 'Downloading...' '%(progress._percent_str)s at %(progress._speed_str)s'" \
    -o "$OUTPUT_TEMPLATE" "$URL"

if [ $? -eq 0 ]; then
    notify-send -i audio-speakers "Download Complete" "Saved to $DEST_DIR"
else
    notify-send -u critical "Download Failed" "Check your connection or URL"
fi
